{{- if or .Values.env .Values.overrides.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8s.configmap" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "app.labels" . | indent 4 }}
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- $emptyList := rest (list 1) }}
  {{-  $env := concat ( default $emptyList .Values.env) (default $emptyList .Values.overrides.env) }}
  {{- range $index, $dict := $env }}
    {{- range $key,$val :=  $dict }}
  {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end -}}  
{{- end }}