image:
  repository: acrweuvecozodemo.azurecr.io/demo-api
  namespace: default
  pullPolicy: Always # using IfNotPresent may lead to issues when node cache get's corrupted
#  tag: "1.0.2"
#  tag: "2.0.0"
  tag: "3.0.0"

service:
  name: demo-api
  type: LoadBalancer
  port: 80
  containerPort: 8080
  internal: true

replicaCount: 2